trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'credifyai'  
  imageName: 'frontend'

steps:
  - checkout: git://credifyai/frontend
    persistCredentials: true
    endpoint: github

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Fetch all tags and commits
        git fetch --tags
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $latest_tag"

        # Parse the version and increment the patch version
        IFS='.' read -r major minor patch <<< "${latest_tag#v}"
        new_patch=$((patch + 1))
        new_version="v$major.$minor.$new_patch"

        echo "New version: $new_version"
        echo "##vso[task.setvariable variable=newVersion]$new_version"

  - task: AzureCLI@2
    inputs:
      azureSubscription: azurerm
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(acrName)

  - task: Docker@2
    displayName: 'Build and Push Multi-Arch Docker Image'
    inputs:
      containerRegistry: acr
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        $(newVersion)  
      arguments: '--platform linux/amd64,linux/arm64'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        git checkout main
        git config user.name "Azure DevOps"
        git config user.email "challagulla.l@northeastern.edu"
        git tag $newVersion
        git push origin $newVersion
