trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'credifyai'  
  imageName: 'frontend'
  tag: 'latest'

steps:
  - checkout: self

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'frontend'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(acrName)

  - task: Docker@2
    displayName: 'Build and Push Multi-Arch Docker Image'
    inputs:
      containerRegistry: '$(acrName).azurecr.io'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'  
      tags: |
        $(tag)
      arguments: '--platform linux/amd64,linux/arm64'
