name: Azure DevOps Pipeline

on:
  pull_request:
    branches:
      - main 

jobs:
  azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipeline
        uses: azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/credifyai/credifyai'
          azure-pipeline-name: 'credifyai' 
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}
